services:
  postgresql_keycloak:
    image: postgres:13
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'postgres'

  keycloak:
    image: quay.io/keycloak/keycloak:21.0.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_DB: postgres
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: password
      KC_DB_URL: jdbc:postgresql://postgresql_keycloak:5432/postgres
      KC_HEALTH_ENABLED: 'true'
      KC_HOSTNAME: elanur.local
      # KC_HOSTNAME_URL: http://elanur.local/keycloak
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_HOST: 0.0.0.0
      KC_LOG_LEVEL: debug
      KC_HTTP_ENABLED: true
    command: >
      start --features=token-exchange --http-relative-path=/keycloak
    ports:
      - '8081:8080'
    depends_on:
      - postgresql_keycloak